apps/contatos/urls.py
from django.urls import path

from . import views

app_name = 'contatos'

urlpatterns = [
    # GET /
    path('', views.TelaInicialView.as_view(), name='tela_inicial'),

    # GET index
    path('dashboard/', views.HomeView.as_view(), name='dashboard'),

    # GET /contatos
    path('contatos/', views.ContatoListView.as_view(), name='lista_contatos'),

    # GET /contatos/cadastrar
    path('contatos/cadastrar/', views.ContatoCreateView.as_view(), name='cadastrar_contato'),

    # GET /contatos/atualizar/<id>
    path('contatos/atualizar/<pk>', views.ContatoUpdateView.as_view(), name='atualizar_contato'),

    # GET /contatos/excluir/<id>
    path('contatos/excluir/<pk>', views.ContatoDeleteView.as_view(), name='excluir_contato'),

    # GET /contatos/detalhes/<id>
    path('contatos/detalhes/<pk>', views.ContatoDetailView.as_view(), name='detalhes_contato'),

]

apps/usuarios/urls.py
from django.urls import path
from . import views


app_name = 'usuarios'

urlpatterns = [
    path('register/', views.SignUpView.as_view(), name='cadastrar_usuario'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
]

setup/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import TemplateView

handler404 = 'contatos.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('contatos.urls', namespace='contato')),
    path('usuarios/', include('usuarios.urls', namespace='usuario')),
    # path('usuarios/', include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/_partials/_footer.html
<footer class="bg-dark text-center text-white fixed-bottom">
    <div class="container p-4 pb-0">
        <section class="">
            <form action="">
                <div class="row d-flex justify-content-center">
                    <div class="col-auto">
                        <p class="pt-2">
                            <strong>Inscreva-se para receber novidades:</strong>
                        </p>
                    </div>

                    <div class="col-md-5 col-10">
                        <div class="form-outline form-white mb-1">
                            <input type="email" id="form5Example29" class="form-control" placeholder="E-mail"/>
                        </div>
                    </div>

                    <div class="col-auto">
                        <button type="submit" class="btn btn-outline-light mb-1">
                            Inscreva-se
                        </button>
                    </div>
                </div>
            </form>
        </section>
        <!-- Section: Form -->
    </div>

    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        Desenvolvido por Matheus Feu
        <a class="text-white" href="#"></a>
    </div>
</footer>

templates/_partials/_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
  {% for error in form.non_field_errors %}
    {{ error }}
  {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="form-group">
  {{ field.label_tag }}

  {% if form.is_bound %}
    {% if field.errors %}
      {% render_field field class="form-control is-invalid" %}
      {% for error in field.errors %}
        <div class="invalid-feedback">
          {{ error }}
        </div>
      {% endfor %}
    {% else %}
      {% render_field field class="form-control is-valid" %}
    {% endif %}
  {% else %}
    {% render_field field class="form-control" %}
  {% endif %}

  {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
  {% endif %}
</div>
{% endfor %}

templates/_partials/_messages.html
{% if messages %}
{% for message in messages %}

<div class="alert {{ message.tags }}" role="alert">
    {{ message }}
</div>

{% endfor %}
{% endif %}

templates/_partials/_navbar.html
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'contatos:dashboard' %}">
            <img src="{% static 'img/favicon.png' %}" height="40px">
        </a>
    {% else %}
        <a class="navbar-brand">
            <img src="{% static 'img/favicon.png' %}" height="40px">
        </a>
    {% endif %}

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudo-navbar"
            aria-controls="conteudo-navbar" aria-expanded="false" aria-label="Ativar navegação">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="conteudo-navbar">
        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contato:dashboard' %}">Página Inicial</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contato:lista_contatos' %}">Contatos</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item active ">
                    <a class="nav-link" href="{% url 'usuarios:logout' %}">Logout</a>
                </li>
            </ul>

        {% else %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'usuarios:login' %}">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'usuarios:cadastrar_usuario' %}">Cadastro</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contatos:tela_inicial' %}">Sobre Mim</a>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>