apps/contatos/urls.py
from django.urls import path

from . import views

app_name = 'contatos'

urlpatterns = [
    # GET /
    path('', views.TelaInicialView.as_view(), name='tela_inicial'),

    # GET index
    path('dashboard/', views.HomeView.as_view(), name='dashboard'),

    # GET /contatos
    path('contatos/', views.ContatoListView.as_view(), name='lista_contatos'),

    # GET /contatos/cadastrar
    path('contatos/cadastrar/', views.ContatoCreateView.as_view(), name='cadastrar_contato'),

    # GET /contatos/atualizar/<id>
    path('contatos/atualizar/<pk>', views.ContatoUpdateView.as_view(), name='atualizar_contato'),

    # GET /contatos/excluir/<id>
    path('contatos/excluir/<pk>', views.ContatoDeleteView.as_view(), name='excluir_contato'),

    # GET /contatos/detalhes/<id>
    path('contatos/detalhes/<pk>', views.ContatoDetailView.as_view(), name='detalhes_contato'),

]

apps/usuarios/urls.py
from django.urls import path
from . import views


app_name = 'usuarios'

urlpatterns = [
    path('register/', views.SignUpView.as_view(), name='cadastrar_usuario'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
]

setup/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import TemplateView

handler404 = 'contatos.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('contatos.urls', namespace='contato')),
    path('usuarios/', include('usuarios.urls', namespace='usuario')),
    # path('usuarios/', include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/contatos/models.py
from django.db import models
from stdimage import StdImageField

from django.contrib.auth import get_user_model
from .choices import *


# Create your models here.
class Contato(models.Model):
    """Classe que representa os dados do contato no banco de dados"""
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE) # Relacionamento com o usuário, para que cada usuário tenha seus contatos
    nome = models.CharField(max_length=150)
    sobrenome = models.CharField(max_length=150, blank=True)
    telefone = models.CharField(max_length=15, unique=True)
    email = models.EmailField(max_length=150, blank=True)
    data_criacao = models.DateTimeField(auto_now_add=True)
    descricao = models.TextField(blank=True)
    categoria = models.CharField(choices=CATEGORIA_CHOICES, max_length=150)
    publicada = models.BooleanField(default=False)
    avatar = StdImageField('Avatar', blank=True, null=True, delete_orphans=True, upload_to='avatars/%Y/%m/%d/')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'
        ordering = ['nome']

apps/contatos/forms.py
from django import forms
# from django.utils import timezone
from django.forms import Textarea
from stdimage import StdImageField

from .choices import *
from .models import Contato


class InsereContatoForm(forms.ModelForm):
    """Esta classe é responsável por criar o formulário de inserção de contatos."""
    nome = forms.CharField(label='Nome', max_length=150,
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome'}))
    sobrenome = forms.CharField(label='Sobrenome', max_length=150, required=False,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sobrenome'}))
    telefone = forms.CharField(label='Telefone', max_length=15,
                               widget=forms.TextInput(attrs={'placeholder': '(11) 99999-9999'}))
    email = forms.EmailField(label='E-mail', max_length=150, required=False)
    descricao = forms.CharField(label='Descrição', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
    categoria = forms.ChoiceField(label='Categoria', choices=CATEGORIA_CHOICES)
    publicada = forms.BooleanField(label='Publicada', required=False, initial=False, widget=forms.CheckboxInput())
    avatar = StdImageField('Avatar', upload_to='Avatars/%Y/%m/%d/')

    class Meta:
        model = Contato
        fields = '__all__'
        exclude = ['user']
        widgets = {
            'descricao': Textarea(attrs={'cols': 80, 'rows': 20}),
        }

    def __init__(self, *args, **kwargs):
        """Esta função acrescente a opção 'Selecione uma categoria' no campo categoria do formulário de inserção de contatos.
        Sendo obrigada a escolher uma categoria para o contato ser inserido no banco de dados."""
        super().__init__(*args, **kwargs)
        self.fields['categoria'].choices = [('', 'Selecione uma categoria')] + CATEGORIA_CHOICES

    def clean_nome(self):
        nome = self.cleaned_data.get('nome')

        if nome:
            nome = nome.strip()
            if ' ' in nome:
                raise forms.ValidationError('O nome não pode conter espaços.')
            elif any(char.isdigit() for char in nome):
                raise forms.ValidationError('O nome não pode conter números.')
            else:
                return nome

    def clean_sobrenome(self):
        sobrenome = self.cleaned_data.get('sobrenome')

        if sobrenome:
            sobrenome = sobrenome.strip()
            if ' ' in sobrenome:
                raise forms.ValidationError('O sobrenome não pode conter espaços')
            elif any(char.isdigit() for char in sobrenome):
                raise forms.ValidationError('O sobrenome não pode conter números')
            else:
                return sobrenome


class AtualizaContatoForm(forms.ModelForm):
    """Esta classe é responsável por criar o formulário de atualização de contatos."""
    nome = forms.CharField(label='Nome', max_length=150,
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome'}))
    sobrenome = forms.CharField(label='Sobrenome', max_length=150, required=False,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sobrenome'}))
    telefone = forms.CharField(label='Telefone', max_length=15,
                               widget=forms.TextInput(attrs={'placeholder': '(11) 99999-9999'}))
    email = forms.EmailField(label='E-mail', max_length=150, required=False)
    # data_criacao = forms.DateTimeField(label='Data de criação',widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'readonly':True}, format='%Y-%m-%dT%H:%M'), initial=timezone.now)
    descricao = forms.CharField(label='Descrição', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
    categoria = forms.ChoiceField(label='Categoria', choices=CATEGORIA_CHOICES)
    publicada = forms.BooleanField(label='Publicada', required=False, initial=True,
                                   widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    avatar = StdImageField('Avatar', upload_to='Avatars/%Y/%m/%d/')

    class Meta:
        model = Contato
        fields = '__all__'
        exclude = ['user']
        widgets = {
            'descricao': Textarea(attrs={'cols': 80, 'rows': 20}),
        }

    def __init__(self, *args, **kwargs):
        """Esta função acrescente a opção 'Selecione uma categoria' no campo categoria do formulário de inserção de contatos.
        Sendo obrigada a escolher uma categoria para o contato ser inserido no banco de dados."""
        super().__init__(*args, **kwargs)
        self.fields['categoria'].choices = [('', 'Selecione uma categoria')] + CATEGORIA_CHOICES

    def clean_nome(self):
        nome = self.cleaned_data.get('nome')

        if nome:
            nome = nome.strip()
            if ' ' in nome:
                raise forms.ValidationError('O nome não pode conter espaços')
            elif any(char.isdigit() for char in nome):
                raise forms.ValidationError('O nome não pode conter números')
            else:
                return nome

apps/contatos/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import render
from django.db.models import Q

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView, DetailView

from .models import Contato
from .forms import InsereContatoForm, AtualizaContatoForm

from django.contrib.auth.mixins import LoginRequiredMixin


class TelaInicialView(TemplateView):
    """Inicia-se na página na pagina inicial do site"""
    template_name = 'telainicial.html'


class HomeView(LoginRequiredMixin, TemplateView):
    """Página inicial do site"""
    template_name = 'dashboard.html'


class ContatoDetailView(LoginRequiredMixin, DetailView):
    """Página de detalhes de contatos"""
    template_name = 'detalhes.html'
    model = Contato


class ContatoListView(LoginRequiredMixin, ListView):
    """Página de listagem de contatos, permite buscar os contatos da agenda e paginação entre eles
    função get_queryset() é responsável por buscar os contatos por nome, telefone e email,
    Q() é um operador lógico do Django que permite fazer buscas por vários campos ao mesmo tempo"""

    template_name = 'contatos.html'
    model = Contato
    context_object_name = 'contatos'
    paginate_by = 3

    def get_queryset(self):
        """Busca os contatos por nome, telefone e email,
        retornando na lista de contatos"""
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)

        search = self.request.GET.get('search')

        # Busca os contatos por nome, telefone e email
        if search:
            qs = qs.filter(
                Q(nome__icontains=search) | Q(telefone__icontains=search) | Q(email__icontains=search))

        return qs


class ContatoUpdateView(LoginRequiredMixin, UpdateView):
    """Página de atualização de contatos, valida se o formulário é
    válido e envia uma mensagem de sucesso na página da lista de contatos"""

    template_name = 'atualiza.html'
    model = Contato
    form_class = AtualizaContatoForm
    success_url = reverse_lazy('contatos:lista_contatos')

    def form_valid(self, form):
        messages.warning(self.request, 'Contato atualizado com sucesso!')
        return super().form_valid(form)


class ContatoCreateView(LoginRequiredMixin, CreateView):
    """Página de cadastro de contatos, se o formulário for válido,
    retorna uma mensagem de sucesso"""

    template_name = 'cria.html'
    model = Contato
    form_class = InsereContatoForm
    success_url = reverse_lazy('contatos:lista_contatos')

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.info(self.request, 'Contato cadastrado com sucesso!')
        return super().form_valid(form)


class ContatoDeleteView(LoginRequiredMixin, DeleteView):
    """Página de exclusão de contatos, se o formulário for válido,
    retorna uma mensagem de sucesso que o contato foi excluído"""

    template_name = 'exclui.html'
    model = Contato
    context_object_name = 'contato'
    success_url = reverse_lazy('contatos:lista_contatos')

    def form_valid(self, form):
        messages.error(self.request, 'Contato excluído com sucesso!')
        return super().form_valid(form)


def handler404(request, exception):
    """Página de erro 404 caso o usuário tente acessar uma página que não existe"""
    return render(request, 'errors/404.html', status=404)

apps/contatos/templates/atualiza.html
{% extends '_layouts/base.html' %}

{% load static %}

{% block title %}Atualização de Contato{% endblock %}

{% block conteudo %}

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Atualização Dados de Contato</h5>
                        <p class="card-text">
                            Complete o formulário abaixo para atualizar o <code>contato</code>.
                        </p>
                        <form method="POST" enctype="multipart/form-data">

                            {% csrf_token %}

                            {% include '_partials/_form.html' %}

                            <div class="text-lg-center mt-3">
                                <button type="submit" class="btn btn-primary">Atualizar Contato</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block endbody %}
    <script src="{% static 'vendor/jquery/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'vendor/jquery/jquery.mask.min.js' %}"></script>
    <script src="{% static 'vendor/js/mask.js' %}" defer></script>
{% endblock %}

apps/contatos/templates/contatos.html
{% extends '_layouts/base.html' %}
{% load static %}

{% load pagination_tags %}

{% block title %}Lista de contatos{% endblock %}


{% block conteudo %}
    <div class="h-100 p-5 bg-light border rounded-4">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <!-- Search -->
                        {% if contatos|length > 0 %}
                            <div class="d-flex flex-row-reverse justify-content-between">
                                <div class="d-flex flex-column justify-content-end pb-3">

                                    <!-- Form Search -->
                                    <form method="GET" id="form-search" action="">
                                        <div class="search-box">
                                            <input name="search" type="text" class="search-txt"
                                                   placeholder="Pesquisar...">
                                            <a onclick="document.getElementById('form-search').submit()"
                                               style="cursor:pointer" class="search-btn">
                                                <img class="loupe-blue" src="{% static 'imgs/loupe-white.svg' %}"
                                                     alt="Lupa" width="20px" height="20px">
                                            </a>
                                        </div>
                                    </form>
                                    <!-- End Form Search -->

                                </div>
                                <div>
                                    <p class="card-text">
                                    <h4 class="card-title">Lista de Contatos</h4>
                                    Aqui está a lista de <code>contatos</code> cadastrados no sistema.
                                    </p>
                                </div>
                            </div>
                            <!-- Fim Search -->

                            <!-- Messages -->
                            {% if messages %}
                                <div class="row justify-content-center mb-2">
                                    <div class="col-2 text-center">
                                        {% include '_partials/_messages.html' %}
                                    </div>
                                </div>
                            {% endif %}
                            <!-- Fim Messages -->

                            <!-- Table -->
                            <table class="table">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Sobrenome</th>
                                    <th scope="col">Telefone</th>
                                    <th scope="col">Categoria</th>
                                    <th scope="col" class="text-center">Ações</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for contato in contatos %}
                                    {% if contato.publicada %}
                                        <tr>
                                            <td>{{ contato.nome }}</td>
                                            <td>{{ contato.sobrenome }}</td>
                                            <td>{{ contato.telefone }}</td>
                                            <td>{{ contato.categoria }}</td>
                                            <td class="text-center">
                                                <div class="d-flex justify-content-center" style="gap:20px">
                                                    <button onclick="ver_contato({{ contato.id }})"
                                                            type="button" class="btn-eyes" data-toggle="modal">
                                                        <i class="fa-solid fa-eye"></i>
                                                    </button>
                                                    <a href="{% url 'contato:atualizar_contato' pk=contato.id %}"
                                                       class="btn-edit">
                                                        <i class="fa-solid fa-edit"></i>
                                                    </a>
                                                    <a href="{% url 'contato:excluir_contato' pk=contato.id %}"
                                                       class="btn-trash">
                                                        <i class="fa-solid fa-trash"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>

                                        <!-- Modal -->
                                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                                             aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered modal-sm"
                                                 role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Detalhes
                                                            do Contato</h5>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                                aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Fim Modal -->

                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                            <!-- Fim Table -->

                            <!-- Paginator -->
                            {% if is_paginated %}
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination justify-content-center">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link"
                                                   href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled">
                                                <a class="page-link" href="#" tabindex="-1"
                                                   aria-disabled="true">&laquo;</a>
                                            </li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class="page-item active" aria-current="page">
                                                    <a class="page-link"
                                                       href="?{% url_replace request 'page' i %}">{{ i }}<span
                                                            class="visually-hidden"></span></a>
                                                </li>
                                            {% else %}
                                                <li class="page-item">
                                                    <a class="page-link"
                                                       href="?{% url_replace request 'page' i %}">{{ i }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                            <li class="page-item">
                                                <a class="page-link"
                                                   href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled">
                                                <a class="page-link" href="#" tabindex="-1"
                                                   aria-disabled="true">&raquo;</a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            {% endif %}
                        {% else %}
                            <!-- End Paginator -->

                            <div class="text-center mt-2 mb-2 jumbotron">
                                <h3>Nenhum <code>contato</code> foi adicionado ainda</h3>
                            </div>
                        {% endif %}
                        <hr/>
                        <div class="btn-lg float-right">
                            <a class="btn btn-primary" href="{% url 'contato:cadastrar_contato' %}">Novo Contato</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block endbody %}
    <script src="{% static 'vendor/js/list.js' %}" defer></script>
    <script src="{% static 'vendor/js/fontawesome.js' %}"></script>
    <script src="{% static 'vendor/js/all.js' %}"></script>
{% endblock %}

apps/contatos/templates/cria.html
{% extends "_layouts/base.html" %}

{% load static %}

{% block title %}Cadastro de Contatos{% endblock %}

{% block conteudo %}

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Cadastro de Contatos</h5>
                        <p class="card-text">
                            Complete o formulário abaixo para cadastrar um novo <code>contatos</code>.
                        </p>

                        <form method="POST" enctype="multipart/form-data">

                            {% csrf_token %}

                            {% include '_partials/_form.html' %}


                            <div class="text-lg-center mt-3">
                                <button type="submit" class="btn btn-primary">Cadastrar Contato</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block endbody %}
 <script src="{% static 'vendor/jquery/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'vendor/jquery/jquery.mask.min.js' %}"></script>
    <script src="{% static 'vendor/js/mask.js' %}" defer></script>
{% endblock %}

apps/contatos/templates/dashboard.html
{% extends '_layouts/base.html' %}

{% block conteudo %}
<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-12 mt-5 text-center">
            <span style="font-size:35px; font-weight: bold">Olá, seja bem vindo {{ user.get_full_name }} a sua agenda!</span>
        </div>
        <div class="col-lg-12">
            <br>
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="card">
                            <div class="card-body"><h4 class="card-title">Cadastrar Contatos</h4>
                                <p class="card-text"> Cadastre aqui um novo <code>contato</code>. </p> <a
                                        href="{% url 'contato:cadastrar_contato' %}" class="btn btn-primary"> Novo Contato </a></div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="card">
                            <div class="card-body"><h4 class="card-title">Lista de Contatos</h4>
                                <p class="card-text"> Veja aqui a lista de <code>contatos</code> cadastrados. </p> <a
                                        href="{% url 'contatos:lista_contatos' %}" class="btn btn-primary">Vá para Lista </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/contatos/templates/detalhes.html
{% load static %}

<h2 class="text-center mb-2">{{ contato.nome }} {{ contato.sobrenome }}</h2>


    {% if contato.avatar == "" or contato.avatar == null %}
    <p>
        <img src="{% static 'img/bonequinho.png' %}" style="max-width:268px; height: auto;">
    </p>
    {% else %}
    <p>
        <img src="{{ contato.avatar.url }}" style="max-width:268px; height: auto;">
    </p>
    {% endif %}


<dl class="text-center">
    <dt>Telefone:</dt>
    <dd>{{ contato.telefone }}</dd>

    <dt>E-mail:</dt>
    <dd>{{ contato.email }}</dd>

    <dt>Data de criação:</dt>
    <dd>{{ contato.data_criacao|date:"d/m/Y" }}</dd>

    <dt>Categoria:</dt>
    <dd>{{ contato.categoria }}</dd>

    <dt>Descrição:</dt>
    <dd>{{ contato.descricao }}</dd>
</dl>

apps/contatos/templates/exclui.html
{% extends '_layouts/base.html' %}

{% block title %}Excluir Contato{% endblock %}


{% block conteudo %}

    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Exclusão de Contato</h5>

                <p class="card-text">
                    Você tem certeza que quer excluir o contato <b>{{ contato.nome }}</b> da sua agenda?
                </p>
                <form method="POST">

                    {% csrf_token %}

                    <hr/>
                    <div class="text-end">
                        <a href="{% url 'contato:lista_contatos' %}" class="btn btn-outline-danger">
                            Cancelar
                        </a>
                        <button class="btn btn-danger">Excluir</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

apps/contatos/templates/telainicial.html
{% extends '_layouts/base.html' %}

{% load static %}

{% block head %}
    <link href="{% static 'vendor/css/inicial.css' %}" rel="stylesheet">
{% endblock %}


{% block conteudo %}

    <div class="py-5">
        <span class="bubble active">Olá, me chamo <strong>Matheus Feu</strong><br>
            Este projeto permite cadastrar, atualizar e organizar seus contatos preferidos.<br>
            Abaixo estão meus links, seguem lá para apoiar!</span>
    </div>

    <div class="circle">
        <img class="" src="{% static 'img/profile.jpg' %}">
    </div>

    <br>
    <div class="jumbotron text-center mt-3">
        <h1 class="display-5">Obrigado!</h1>
        <p class="lead"><strong>Me siga nas redes sociais</strong> para obter mais informações sobre mim.
        </p>

        <hr>
        <p>
            Mais sobre mim? <a href="https://www.linkedin.com/in/matheus-feu-558558186/">Entre em contato</a>
        </p>
        <p class="lead">
            <a class="btn btn-primary btn-sm" href="{% url 'usuarios:cadastrar_usuario' %}"
               role="button">Cadastre-se</a>
        </p>
    </div>

    {% include '_partials/_footer.html' %}

{% endblock %}